  version: '3.8'

  services:
    mysql:
      image: mysql:8.0
      container_name: mysql-vollmed
      restart: always
      ports:
        - "3307:3306"   # <- alterado aqui
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: vollmed_api
      volumes:
        - mysql_data:/var/lib/mysql

  volumes:
    mysql_data:
